name: ecommerce

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    env_file:
      - path: ./services/.env
        required: false
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  user_service:
    build:
      context: .
      dockerfile: ./services/user_service/Dockerfile
    container_name: user_service_container
    env_file:
      - path: ./services/.env
        required: false
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  product_service:
    build:
      context: ./services/product_service
      dockerfile: Dockerfile
    container_name: product_service_container
    env_file:
      - path: ./services/product_service/.env
        required: false
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  cart_service:
    build:
      context: .
      dockerfile: ./services/cart_service/Dockerfile
    container_name: cart_service_container
    env_file:
      - path: ./services/.env
        required: false
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5


volumes:
  pg_data:

networks:
  app-network:
